# Show help for custom commands and notable Brewfile tools
# Source: https://github.com/JamalLyons/my-shell
function helpme
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  my-shell — Fish custom commands"
    echo "  https://github.com/JamalLyons/my-shell"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "  Configuration:"
    echo "    helpme          - Show this help"
    echo "    reload          - Reload fish configuration"
    echo "    editfish        - Open fish config in \$EDITOR"
    echo "    editenv         - Open local env vars in \$EDITOR"
    echo "    brewup          - Update Homebrew formulas, casks, and Fisher"
    echo "    local.fish      - Private env vars: ~/.config/fish/conf.d/local.fish"
    echo ""
    echo "  Xcode:"
    echo "    xcodes install --latest --select"
    echo "    xcodes installed / xcodes list"
    echo ""
    echo "  File operations:"
    echo "    mkcd <dir>      - Create directory and cd into it"
    echo "    extract <file>  - Extract common archive formats"
    echo "    ff <name>       - Find files by name"
    echo "    fdir <name>     - Find directories by name"
    echo "    duh             - Disk usage of current directory"
    echo "    cleanup         - Remove .DS_Store files under ."
    echo "    ql <file>       - Open file in Quick Look"
    echo "    cdf             - cd to frontmost Finder window"
    echo ""
    echo "  macOS:"
    echo "    showfiles       - Show hidden files in Finder"
    echo "    hidefiles       - Hide hidden files in Finder"
    echo "    flushdns        - Flush DNS cache"
    echo "    path            - Print PATH one entry per line"
    echo ""
    echo "  Development:"
    echo "    serve [port]    - HTTP server (default 8000)"
    echo "    ports           - Show listening ports"
    echo "    myip            - Public IP"
    echo "    weather         - Short weather forecast"
    echo "    note [text]     - Add or list quick notes (~/.notes)"
    echo "    beep / cls      - Terminal beep / clear"
    echo ""
    echo "  Git credentials:"
    echo "    git-cred-clear              - Clear GitHub keychain entry"
    echo "    git-cred-update <user> <token>"
    echo "    git-cred-view               - Show GitHub username"
    echo ""
    echo "  Git aliases:"
    echo "    gs ga gc gp gl gd gb gco gst gsp"
    echo ""
    echo "  Git abbreviations (type + space to expand):"
    echo "    gst → git status       gco → git checkout"
    echo "    gaa → git add --all    gcm → git commit -m"
    echo "    gps → git push         gpl → git pull"
    echo "    gd  → git diff         gl  → git log (graph)"
    echo ""
    echo "  Docker (when docker is installed):"
    echo "    d dc dps dpa di dex"
    echo ""
    echo "  Brewfile tools (if installed):"
    echo "    fnm …          - Node versions (fnm list / install lts / use)"
    echo "    z <query>      - zoxide smart cd"
    echo "    ll / la / l    - eza listings (falls back to ls)"
    echo "    cat            - bat when available"
    echo "    rg / fd / fzf  - search tools (fzf keybindings in interactive fish)"
    echo "    tide configure - Customize Tide prompt"
    echo ""
    echo "  Edit templates in the GitHub repo, then re-run:"
    echo "    bash ./setup.sh"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
end
